const { Sequelize } = require("sequelize");
require("dotenv").config();

const tenantDatabase = new Sequelize(
  process.env.TENANT_DB_NAME || "",
  process.env.MAIN_DB_USER,
  process.env.MAIN_DB_PASSWORD,
  {
    host: process.env.MAIN_DB_HOST,
    port: process.env.MAIN_DB_PORT,
    dialect: "mysql",
    logging: false,
  }
);

const connectTenantDatabase = async () => {
  try {
    await tenantDatabase.authenticate();

    console.log("Tenant database connected successfully");

    return tenantDatabase;
  } catch (error) {
    console.error(
      "Tenant database connection failed:",
      error.message
    );

    throw error;
  }
};

const createTenantDatabase = async (databaseName) => {
  // Connection without selecting a database
  const sequelize = new Sequelize(
    "",
    process.env.MAIN_DB_USER,
    process.env.MAIN_DB_PASSWORD,
    {
      host: process.env.MAIN_DB_HOST,
      port: process.env.MAIN_DB_PORT,
      dialect: "mysql",
      logging: false,
    }
  );

  try {
    await sequelize.authenticate();

    // Database name is generated by our backend
    await sequelize.query(
      `CREATE DATABASE IF NOT EXISTS \`${databaseName}\``
    );

    console.log(`Tenant database created: ${databaseName}`);

    await sequelize.close();

    return true;
  } catch (error) {
    await sequelize.close();

    console.error(
      "Tenant database creation failed:",
      error.message
    );

    throw error;
  }
};

module.exports = {
  createTenantDatabase,
  tenantDatabase,
  connectTenantDatabase,
};